name: diff

outputs:
  diff-count:
    value: ${{ steps.diff.outputs.diff-count }}

runs:
  using: composite
  steps:
    - id: diff
      run: |
        git fetch origin main
        count=`git diff origin/main HEAD --name-only -- go.mod go.sum | wc -l`
        echo "::set-output name=diff-count::$(echo $count)"
      shell: bash
