name: deploy

on:
  repository_dispatch:
    types:
      - deploy

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: "1.16.7"

      - name: go mod tidy
        run: go mod tidy

      - name: git setting
        run: |
          git config --local user.email "s.datsukan@gmail.com"
          git config --local user.name "datsukan"

      - name: commit files
        run: |
          git add -A
          git commit -m "go mod tidy"
          git pull
          git push origin main
