name: deploy

on:
  repository_dispatch:
    types:
      - deploy

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: go module update
        run: |
          go get github.com/datsukan/datsukan-blog-good-core
          go get github.com/datsukan/datsukan-blog-good-lambda-frame

      - name: diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true

      - name: git setting & commit & push
        run: |
          git config --local user.email "s.datsukan@gmail.com"
          git config --local user.name "datsukan"
          git pull
          git add -A
          git commit -m "go module update"
          git push origin main
        if: steps.diff.outcome == 'failure'
